### ISSUE TITLE
Updated code? 

### ISSUE THREAD

**Issue by geeknik** [ToChunkaA/Smart-TabS#1]
Thanks for the interesting browser extension and for supporting Firefox. 🔥🦊  Any chance you can push out your latest code? It appears to have gotten a bit stale in here. 😀

**Comment by ToChunkA** [comment]
Hello, @geeknik.

Thanks for the feedback.

Yes, just started the next development sprint which includes GitHub updates.

**Comment by geeknik** [comment]
Awesome, can't wait to see what's next for this extension. Thanks for the update!

**Comment by ToChunkA** [comment]
You can suggest specific changes if you have some.
